# Module: NumPy Assignments

## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation


1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,21, size=(5,5))
print(arr)

[[ 7  7  6  6  4]
 [ 5  5  8  7 13]
 [ 8  1 11  8 19]
 [ 7 15 13 12 10]
 [ 7  3 14 17  6]]


In [3]:
arr[:, 2] = 1
print(arr)

[[ 7  7  1  6  4]
 [ 5  5  1  7 13]
 [ 8  1  1  8 19]
 [ 7 15  1 12 10]
 [ 7  3  1 17  6]]


In [4]:
arr2 = np.arange(1,17).reshape(4,4)

np.fill_diagonal(arr2, 0)
print(arr2)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [5]:
arr_ind = np.arange(1,37).reshape(6,6)
print(arr_ind)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [6]:
subarr_ind = arr_ind[2:5, 1:4]
print(subarr_ind)

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [7]:
arr_ind2 = np.random.randint(1, 51, size=(5,5))
print(arr_ind2)


[[33 41 21  2 36]
 [24  5 43 13 34]
 [ 7 42  1 21  4]
 [ 9 15 38  1  9]
 [45 46 14 29 25]]


In [8]:
top_row = arr_ind2[0, :]
print(top_row)

bottom_row = arr_ind2[-1, :]
print(bottom_row)

left_column = arr_ind2[:, 0]
print(left_column)

right_column = arr_ind2[:, -1]
print(right_column)

border_element = np.concatenate([top_row, right_column, bottom_row[::-1], left_column[::-1]], axis=0)
print(border_element)

[33 41 21  2 36]
[45 46 14 29 25]
[33 24  7  9 45]
[36 34  4  9 25]
[33 41 21  2 36 36 34  4  9 25 25 29 14 46 45 45  9  7 24 33]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [9]:
np.random.seed(42)
arr_ops1 = np.random.randint(1,11, size=(3,4))
arr_ops2 = np.random.randint(1,11, size=(3,4))

addition = arr_ops1 + arr_ops2
subtraction = arr_ops1 - arr_ops2
multiplication = arr_ops1 * arr_ops2
division = arr_ops1 / arr_ops2

print(addition)
print(subtraction)
print(multiplication)
print(division)

[[15  7 14 10]
 [ 9 18  9  9]
 [13  6 14 14]]
[[-1  1  2  0]
 [ 5  2 -3  5]
 [ 3  4 -6  2]]
[[56 12 48 25]
 [14 80 18 14]
 [40  5 40 48]]
[[0.875      1.33333333 1.33333333 1.        ]
 [3.5        1.25       0.5        3.5       ]
 [1.6        5.         0.4        1.33333333]]


In [10]:
arr_broad = np.arange(1,17).reshape(4,4)
print(arr_broad)

col_sum = np.sum(arr_broad, axis=0)
print(col_sum)

row_sum = np.sum(arr_broad, axis=1)
print(row_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[28 32 36 40]
[10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [11]:
np.random.seed(42)
arr_random = np.random.randint(1,101, size=(5,5))
print(arr_random)

random_mean = np.mean(arr_random)
print(random_mean)
median_val = np.median(arr_random)
print(median_val)
std_val = np.std(arr_random)
print(std_val)
var_val = np.var(arr_random)
print(var_val)

[[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]]
50.48
53.0
30.899993527507412
954.8095999999999


In [12]:
arr_stat = np.arange(1,10).reshape(3,3)
print(arr_stat)

mu = np.mean(arr_stat)
sigma = np.std(arr_stat)

normalized_arr = (arr_stat - mu) / sigma
print(normalized_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [21]:
np.random.seed(42)

# 1. Create the 3x3 array
arr_broadcasting = np.random.randint(1, 11, size=(3, 3))

# 2. Create a TRUE 1D array of shape (3,)
# This will be treated as a row that gets added to every row below it
arr_small = np.random.randint(1, 4, size=(3,))

# 3. Add them together
arr_board_sum = arr_broadcasting + arr_small

print("2D Array:\n", arr_broadcasting)
print("\n1D Array (Shape (3,)): ", arr_small)
print("\nResult:\n", arr_board_sum)

2D Array:
 [[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

1D Array (Shape (3,)):  [1 3 2]

Result:
 [[ 8  7 10]
 [ 6 10 12]
 [ 4 10 10]]


In [24]:
arr_broad_sec = np.random.randint(1,17, size=(4,4))
arr_small_2 = np.random.randint(1, 5, size=(4,))

arr_board_sub = arr_broad_sec - arr_small_2.reshape(4,1)
print(arr_board_sub)

[[-1  3  1  5]
 [ 3 -2  0  5]
 [ 9 11 -1  7]
 [ 5  6  1 -2]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [25]:
np.random.seed(42)

matrix = np.random.randint(1, 10, size=(3, 3))

det = np.linalg.det(matrix)
inv = np.linalg.inv(matrix)
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:\n", matrix)
print("\nDeterminant:", det)
print("\nInverse:\n", inv)
print("\nEigenvalues:", eigenvalues)

Matrix:
 [[7 4 8]
 [5 7 3]
 [7 8 5]]

Determinant: -11.00000000000003

Inverse:
 [[-1.         -4.          4.        ]
 [ 0.36363636  1.90909091 -1.72727273]
 [ 0.81818182  2.54545455 -2.63636364]]

Eigenvalues: [17.90450054 -0.40849315  1.50399261]


In [26]:
matrix_A = np.random.randint(1, 10, size=(2, 3)) # Shape (2, 3)
matrix_B = np.random.randint(1, 10, size=(3, 2)) # Shape (3, 2)

result = matrix_A @ matrix_B

print("Matrix A (2x3):\n", matrix_A)
print("\nMatrix B (3x2):\n", matrix_B)
print("\nProduct (2x2):\n", result)

Matrix A (2x3):
 [[4 8 8]
 [3 6 5]]

Matrix B (3x2):
 [[2 8]
 [6 2]
 [5 1]]

Product (2x2):
 [[96 56]
 [67 41]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [32]:
arr_shape = np.arange(1,10).reshape(3,3)
print(arr_shape)

arr_19 = arr_shape.reshape(1,9)
# -1 shortcut
arr_19_short = arr_shape.reshape(1,-1)
print(arr_19_short)

arr_91 = arr_shape.reshape(9,1)
# -1 shortcut
arr_91_short = arr_shape.reshape(-1, 1)
print(arr_91_short)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [36]:
arr_f = np.random.randint(1, 100, size=(5, 5))
print("Original 5x5 Array:\n", arr)

arr_flat = arr.flatten()
print("\nFlattened Array (Shape 25,):\n", arr_flat)

arr_back = arr_flat.reshape(5, 5)
print("\nReshaped Back to 5x5:\n", arr_back)

Original 5x5 Array:
 [[ 7  7  1  6  4]
 [ 5  5  1  7 13]
 [ 8  1  1  8 19]
 [ 7 15  1 12 10]
 [ 7  3  1 17  6]]

Flattened Array (Shape 25,):
 [ 7  7  1  6  4  5  5  1  7 13  8  1  1  8 19  7 15  1 12 10  7  3  1 17
  6]

Reshaped Back to 5x5:
 [[ 7  7  1  6  4]
 [ 5  5  1  7 13]
 [ 8  1  1  8 19]
 [ 7 15  1 12 10]
 [ 7  3  1 17  6]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [40]:
# 1. Create a 5x5 array of random integers
np.random.seed(10)
arr_fa = np.random.randint(1, 101, size=(5, 5))

rows = [0, 0, 4, 4]
cols = [0, 4, 0, 4]

corners = arr_fa[rows, cols]

print("Original Array:\n", arr_fa)
print("\nExtracted Corners:", corners)

Original Array:
 [[10 16 65 29 90]
 [94 30  9 74  1]
 [41 37 17 12 55]
 [89 63 34 73 79]
 [50 52 55 78 70]]

Extracted Corners: [10 90 50 70]


In [41]:
np.random.seed(42)
arr_boo = np.random.randint(1, 21, size=(4, 4))

print("Original Array:\n", arr_boo)

arr_boo[arr_boo > 10] = 10
print("\nModified Array (Capped at 10):\n", arr_boo)

Original Array:
 [[ 7 20 15 11]
 [ 8  7 19 11]
 [11  4  8  3]
 [ 2 12  6  2]]

Modified Array (Capped at 10):
 [[ 7 10 10 10]
 [ 8  7 10 10]
 [10  4  8  3]
 [ 2 10  6  2]]


In [43]:
new_arr_bool = np.where(arr_boo > 10, 10, arr_boo)
print(new_arr_bool)

[[ 7 10 10 10]
 [ 8  7 10 10]
 [10  4  8  3]
 [ 2 10  6  2]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [46]:
dt = np.dtype([('name', 'U20'), ('age', 'i4'), ('weight', 'f4')])

data = [
    ('Alice', 25, 62.5),
    ('Bob', 19, 80.2),
    ('Charlie', 32, 75.0),
    ('Diana', 22, 58.9)
]

structured_arr = np.array(data, dtype=dt)
sorted_arr = np.sort(structured_arr, order='age')

print("Original Structured Array:")
print(structured_arr)

print("\nSorted by Age:")
print(sorted_arr)

Original Structured Array:
[('Alice', 25, 62.5) ('Bob', 19, 80.2) ('Charlie', 32, 75. )
 ('Diana', 22, 58.9)]

Sorted by Age:
[('Bob', 19, 80.2) ('Diana', 22, 58.9) ('Alice', 25, 62.5)
 ('Charlie', 32, 75. )]


In [47]:
dt = np.dtype([('x', 'i4'), ('y', 'i4')])
points = np.array([(1, 2), (4, 6), (5, 1), (8, 4)], dtype=dt)

x = points['x']
y = points['y']

dist_matrix = np.sqrt((x[:, np.newaxis] - x)**2 + (y[:, np.newaxis] - y)**2)

print("Points:\n", points)
print("\nPairwise Distance Matrix:\n", dist_matrix)

Points:
 [(1, 2) (4, 6) (5, 1) (8, 4)]

Pairwise Distance Matrix:
 [[0.         5.         4.12310563 7.28010989]
 [5.         0.         5.09901951 4.47213595]
 [4.12310563 5.09901951 0.         4.24264069]
 [7.28010989 4.47213595 4.24264069 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [56]:
import numpy.ma as ma

np.random.seed(25)
data = np.random.randint(1,21, size=(4,4))

masked_arr = ma.masked_where(data > 10, data)
unmasked_sum = masked_arr.sum()

print("Original Data:\n", data)
print("\nMasked Array:\n", masked_arr)
print("\nSum of unmasked elements:", unmasked_sum)

Original Data:
 [[ 5 16 13 19]
 [ 9  5  6  2]
 [ 8  4  4 14]
 [ 4  2 17 16]]

Masked Array:
 [[5 -- -- --]
 [9 5 6 2]
 [8 4 4 --]
 [4 2 -- --]]

Sum of unmasked elements: 49


In [61]:
np.random.seed(42)
data2 = np.random.randint(1, 10, size=(3, 3))

diag_mask = np.eye(3,dtype=bool)

masked_arr2 = ma.masked_array(data2, mask=diag_mask)

unmasked_mean = masked_arr2.mean()

filled_arr2 = masked_arr2.filled(unmasked_mean)

print("Original Array:\n", data2)
print("\nMasked Array (Diagonal hidden):\n", masked_arr2)
print(f"\nMean of unmasked elements: {unmasked_mean:.2f}")
print("\nFinal Array (Masked values replaced by mean):\n", filled_arr2)

Original Array:
 [[7 4 8]
 [5 7 3]
 [7 8 5]]

Masked Array (Diagonal hidden):
 [[-- 4 8]
 [5 -- 3]
 [7 8 --]]

Mean of unmasked elements: 5.83

Final Array (Masked values replaced by mean):
 [[5 4 8]
 [5 5 3]
 [7 8 5]]
